# Guest OS timezone
timezone: Europe/Kiev

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: metalpark

# Virtual machine IP
ip: 192.168.100.137

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
