version: '2'
services:
  php:
    image: dmstr/php-yii2:7.2-fpm-4.7-alpine-nginx
    environment:
      YII_ENV_DEV: 1
      YII_DEBUG: 1
      DISPLAY_PHP_ERRORS: 1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated
    ports:
      - '8000:80'

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metalpark
      MYSQL_USER: metalpark
      MYSQL_PASSWORD: metalpark
      TZ: Europe/Kiev
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
